# Generated by Django 4.2 on 2026-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_recuperacao',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao-binario', 'Não-binário'), ('outro', 'Outro'), ('prefiro-nao-dizer', 'Prefiro não dizer')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_exibicao',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
